### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by asprakash** [zaiddabaeen/XBeeIOIO#1]
Its a interesting project since we are using IOIO for few years. As you mentioned, there is some documents available for XBeeIOIO. But I could not able to find any one on the root folder. Can you please point the same?. So that I can also contribute to prepare some docs.

Thanks in adv,
Prakash

**Comment by zaiddabaeen** [comment]
The JavaDoc has been generated again and is available in the doc folder.

**Comment by asprakash** [comment]
Thanks. Fixed. Will get back to you once I prepared some Howto tutorial to kick start the XBeeIOIO.
